language: node_js
node_js:
  - '10'
before_install:
  - sudo apt-get install -y libsecret-1-dev
install:
  - npm install
script:
  - npm run check-code
  - npm run build
addons:
  apt:
    update: true
